# E-choppers met een QR-code naar hun digitale huurovereenkomst.
# De URL wordt: /verhuur-e-chopper-nummer-<nr>-met-kenteken-<kenteken>/
# Deze URL's staan op de QR-stickers: bestaande regels niet wijzigen, alleen toevoegen.
ECHOPPERS = [
    (1, "kenteken-verwijderd"),
    (2, "kenteken-verwijderd"),
    (3, "kenteken-verwijderd"),
    (4, "kenteken-verwijderd"),
    (5, "kenteken-verwijderd"),
    (6, "kenteken-verwijderd"),
    (7, "kenteken-verwijderd"),
    (8, "kenteken-verwijderd"),
    (9, "kenteken-verwijderd"),
    (10, "kenteken-verwijderd"),
    (11, "kenteken-verwijderd"),
    (12, "kenteken-verwijderd"),
    (13, "kenteken-verwijderd"),
    (14, "kenteken-verwijderd"),
    (15, "kenteken-verwijderd"),
    (16, "kenteken-verwijderd"),
    (17, "kenteken-verwijderd"),
    (18, "kenteken-verwijderd"),
    (19, "kenteken-verwijderd"),
    (20, "kenteken-verwijderd"),
    (21, "kenteken-verwijderd"),
    (22, "kenteken-verwijderd"),
    (23, "kenteken-verwijderd"),
    (24, "kenteken-verwijderd"),
    (25, "kenteken-verwijderd"),
    (26, "kenteken-verwijderd"),
    (27, "kenteken-verwijderd"),
    (28, "kenteken-verwijderd"),
    (29, "kenteken-verwijderd"),
    (30, "kenteken-verwijderd"),
]
